Repository rabbitmq/rabbitmq-stream-java-client, pull requests merged in 2024-10, with the labels that each got.

#627 Check producer name is less than 256-byte long
  src/main/java/com/rabbitmq/stream/impl/Client.java
Labels: bug

#628 Check producer name is less than 256-byte long
  src/main/java/com/rabbitmq/stream/impl/StreamConsumerBuilder.java
Labels: usability

#635 Add initial member count to stream creator
  src/main/java/com/rabbitmq/stream/StreamCreator.java
  src/main/java/com/rabbitmq/stream/impl/Client.java
  src/main/java/com/rabbitmq/stream/impl/StreamStreamCreator.java
  src/test/java/com/rabbitmq/stream/impl/StreamEnvironmentTest.java
Labels: enhancement

#637 Support arbitrary key-value argument in stream creator
  src/main/java/com/rabbitmq/stream/StreamCreator.java
  src/main/java/com/rabbitmq/stream/impl/Client.java
  src/main/java/com/rabbitmq/stream/impl/StreamStreamCreator.java
Labels: enhancement

#642 optional retry on recovery
  src/docs/asciidoc/api.adoc
  src/main/java/com/rabbitmq/stream/ProducerBuilder.java
  src/main/java/com/rabbitmq/stream/impl/StreamProducer.java
  src/main/java/com/rabbitmq/stream/impl/StreamProducerBuilder.java
  src/test/java/com/rabbitmq/stream/impl/StreamProducerTest.java
  src/test/java/com/rabbitmq/stream/impl/StreamProducerUnitTest.java
Labels: enhancement
